### PR TITLE
make print() work for python3. small format changes.

### PR DESCRIPTION
**Pull request by esvhd**
Hi there,

I added a few minor changes to make the code work for Python 3.x. Hope this helps.

Thanks.

### CODE REVIEW

**Comment by iisayoo** [comment]
Thanks for the changes. 

Your change `if self.trace is True:` is redundant, as is the original `is self.trace == True:`. It would be better to replace it with simply `if self.trace:`. If you're willing to make this modification, I'll be happy to merge it.

**Comment by esvhd** [comment]
Hi there,

Yea I changed == to "is" but now thinking about it, it would be more pythonic if it is just:

If x:
    #code

What do you think?

Thanks.

**Comment by iisayoo** [comment]
See my first comment. I have already merged that change. Thanks.

**Comment by esvhd** [comment]
Sorry, missed that. All good. 

Thanks.

**Pull request merged**
